import Head from "next/head";

import {
  Layout,
  Hero,
  About,
  OtherProjects,
  Contact,
  Experience,
  Projects,
} from "@components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wagdy Samih | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Experience />
        <Projects />
        <OtherProjects />
        <Contact />
      </Layout>
    </>
  );
}
